#ifndef __ACTION_DEF_H__
#define __ACTION_DEF_H__

#define CNT_ITEM_PER_ACTION 14
#define ACTION_STRIDE 7
#define ACTION_SPEED_INDEX 12
#define ACTION_STRIDE_INDEX 13


#include "typedef.h"

#define CNT_ACTION_FORWARD 24
extern u8 code ACT_FORWORD[CNT_ACTION_FORWARD][CNT_ITEM_PER_ACTION];

#endif