#ifndef __ACTION_DEF_H__
#define __ACTION_DEF_H__

#define CNT_ITEM_PER_ACTION 14
#define ACTION_STRIDE 7
#define ACTION_SPEED_INDEX 12
#define ACTION_STRIDE_INDEX 13


#include "typedef.h"

#define CNT_ACTION_TO_INIT 1
extern u8 code ACT_TO_INIT[CNT_ACTION_TO_INIT][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_FORWARD 4
extern u8 code ACT_FORWORD[CNT_ACTION_FORWARD][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_BACKWARD 4
extern u8 code ACT_BACKWORD[CNT_ACTION_BACKWARD][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_TURN_LEFT 4
extern u8 code ACT_TURN_LEFT[CNT_ACTION_TURN_LEFT][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_TURN_RIGHT 4
extern u8 code ACT_TURN_RIGHT[CNT_ACTION_TURN_RIGHT][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_ROCK 4
extern u8 code ACT_ROCK[CNT_ACTION_ROCK][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_WANGTIAN 3
extern u8 code ACT_WANGTIAN[CNT_ACTION_WANGTIAN][CNT_ITEM_PER_ACTION];

#define CNT_ACTION_DANCE 4
extern u8 code ACT_DANCE[CNT_ACTION_DANCE][CNT_ITEM_PER_ACTION];


#define ACTION_TO_INIT			99
#define ACTION_NONE		 			0
#define ACTION_FORWARD 			1
#define ACTION_BACKWARD 		2
#define ACTION_TURN_LEFT	 	3
#define ACTION_TURN_RIGHT 	4
#define ACTION_WANGTIAN			8
#define ACTION_DANCE			 	9
#define ACTION_ROCK 				10


#endif